language: android
sudo: false ## Enable container-based infrastructure
android:
  components:
    - build-tools-23.0.1
    - android-23
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_install:
    - chmod +x gradlew
    - chmod +x scripts/do.sh
script:
    - ./scripts/do.sh
after_script:
    - echo file:///home/travis/build/stoyicker/AligningRecyclerView/library/build/outputs/lint-results.html
